name: "CI"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nixbuild/nix-quick-install-action@v21
      with:
        nix_conf: |
          experimental-features = nix-command flakes
    - name: Build and test 🔧
      run: nix build -j 4 -L
    - name: Build and test (GHC 8.8) 🔧
      run: nix build -j 4 -L .#jrec-ghc88
