name: "CI"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nixbuild/nix-quick-install-action@v21
    - uses: cachix/cachix-action@v6
      with:
        name: juspay-nau
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        # Only needed for private caches
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build and test 🔧
      run: nix build -j 4 -L
